# Nog wat numpy indexing

In [8]:
import numpy as np

# Create a sample NumPy array with shape (4, 6, 3)
# For demonstration purposes, let's generate random RGB values
# genai_arr = np.random.randint(0, 256, size=(4, 6, 3))  # Random RGB values between 0 and 255
genai_arr = np.arange(4*6*3)
genai_arr = genai_arr.reshape(4,6,3)
# Print the original array
print(f"Original Array (shape {genai_arr.shape}):\n{genai_arr}")

# Extract the red values (first channel)
red_values = genai_arr[:, :, 0]  # Select all rows and columns, and the first channel (R)
print(red_values)
# Flatten the array to get a list of all R values
red_values_flattened = red_values.flatten()

# Print the result
print("Red Values (flattened):\n", red_values_flattened)

Original Array (shape (4, 6, 3)):
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]
  [48 49 50]
  [51 52 53]]

 [[54 55 56]
  [57 58 59]
  [60 61 62]
  [63 64 65]
  [66 67 68]
  [69 70 71]]]
[[ 0  3  6  9 12 15]
 [18 21 24 27 30 33]
 [36 39 42 45 48 51]
 [54 57 60 63 66 69]]
Red Values (flattened):
 [ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69]


In [2]:
arr_2 = genai_arr.reshape(4,6,3)
arr_2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47],
        [48, 49, 50],
        [51, 52, 53]],

       [[54, 55, 56],
        [57, 58, 59],
        [60, 61, 62],
        [63, 64, 65],
        [66, 67, 68],
        [69, 70, 71]]])

In [9]:
# Dit geeft hetzelfde resultaat
print(f"Alles 1\n {arr_2[:,:,:]}") # selecteer van alle kanalen alles
print(f"Alles 2\n {arr_2[:,:]}") # selecteer van alle kanalen alles
print(f"Alles 3\n {arr_2[:]}") # selecteer van alle kanalen alles


Alles 1
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]
  [48 49 50]
  [51 52 53]]

 [[54 55 56]
  [57 58 59]
  [60 61 62]
  [63 64 65]
  [66 67 68]
  [69 70 71]]]
Alles 2
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]
  [48 49 50]
  [51 52 53]]

 [[54 55 56]
  [57 58 59]
  [60 61 62]
  [63 64 65]
  [66 67 68]
  [69 70 71]]]
Alles 3
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]
  [48 49 50]
  [51 52 53]]

 [[54 55 56]
  [57 58 59]
  [60 61 62]
  [63 64 65]
  [66 67 68]
  [69 70 71]]]


In [10]:
# Dit geeft ook hetzelfde element
print(f"Eerste element 1\n {arr_2[0]}")
print(f"Eerste element 2\n {arr_2[:,:,:][0]}") # selecteer van alle kanalen alles
print(f"Eerste element 3\n {arr_2[:,:][0]}") # selecteer van alle kanalen alles
print(f"Eerste element 4\n {arr_2[:][0]}") # selecteer van alle kanalen alles


Eerste element 1
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
Eerste element 2
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
Eerste element 3
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
Eerste element 4
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [14]:
# Alles van het eerste "kanaal" alleen de eerste 2 van het tweede kanaal
arr_2[:,0:2,0]

array([[ 0,  3],
       [18, 21],
       [36, 39],
       [54, 57]])

In [15]:
arr_2[:,0:2,0][0] # Het eerste element hiervan

array([0, 3])

In [16]:
arr_2[:,0:2,:] # alle elementen van de subselectie

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[36, 37, 38],
        [39, 40, 41]],

       [[54, 55, 56],
        [57, 58, 59]]])

In [21]:
arr_2[:,0:2,1:3] # alleen het tweede en derde element (vanaf 1 to 3 not included)

array([[[ 1,  2],
        [ 4,  5]],

       [[19, 20],
        [22, 23]],

       [[37, 38],
        [40, 41]],

       [[55, 56],
        [58, 59]]])

In [22]:
arr_2[:,:,1:3] # alle kanalen dimensie 1 alles dimensie 2 tergi 2de en 3de

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11],
        [13, 14],
        [16, 17]],

       [[19, 20],
        [22, 23],
        [25, 26],
        [28, 29],
        [31, 32],
        [34, 35]],

       [[37, 38],
        [40, 41],
        [43, 44],
        [46, 47],
        [49, 50],
        [52, 53]],

       [[55, 56],
        [58, 59],
        [61, 62],
        [64, 65],
        [67, 68],
        [70, 71]]])

In [23]:
arr_2[:,:,1:3][0] # alleen het eerste resultaat

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11],
       [13, 14],
       [16, 17]])

In [24]:
arr_2[:,:,2] # elke derde element

array([[ 2,  5,  8, 11, 14, 17],
       [20, 23, 26, 29, 32, 35],
       [38, 41, 44, 47, 50, 53],
       [56, 59, 62, 65, 68, 71]])

In [25]:
arr_2[:,:,2:3] # elke derde element apart

array([[[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]],

       [[20],
        [23],
        [26],
        [29],
        [32],
        [35]],

       [[38],
        [41],
        [44],
        [47],
        [50],
        [53]],

       [[56],
        [59],
        [62],
        [65],
        [68],
        [71]]])

In [26]:
arr_2[:,:,2].flatten()

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50,
       53, 56, 59, 62, 65, 68, 71])

In [28]:
arr_2.size

72

In [29]:
len(arr_2)

4