In [2]:
import numpy as np

# Intro

In [4]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [5]:
nested_list = [[1,2], [3,4], [5,6]]
nested_list

[[1, 2], [3, 4], [5, 6]]

In [8]:
a1 = np.array(nested_list)
a1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
a2 = np.arange(0, 10, 2)
a2

array([0, 2, 4, 6, 8])

In [24]:
az = np.zeros((3,2))
az

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
az2 = np.zeros((4,3), dtype=int)
a1s = np.ones((4,3), dtype=int)
az2, a1s

(array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]),
 array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]))

In [21]:
a_lin = np.linspace(0, 10, 21)  # Evenly spaced points (linearly spaced)
a_lin

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [23]:
m = np.eye(5) # Identity matrix
m

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
# random
print(np.random.rand(2))
print(np.random.randn(3,4))

[0.35607144 0.74889785]
[[ 0.56581713  2.81532871  0.59424798 -0.60524377]
 [ 0.41079703 -0.23793628  0.03629088  1.42788483]
 [ 0.12805449 -2.05426333  1.50253306 -0.38667694]]


In [30]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [33]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)
print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[38 18 22 10 10 23 35 39 23  2]


In [34]:
arr.shape

(25,)

In [37]:
arr55 = arr.reshape(5,5)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
arr55

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [41]:
ranarr.max()

np.int64(39)

In [42]:
ranarr.argmax()

np.int64(7)

In [43]:
ranarr.min()

np.int64(2)

In [44]:
ranarr.argmin()

np.int64(9)

In [45]:
ranarr.dtype

dtype('int64')

# Selection

In [ ]:
import numpy as np

In [47]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr[8]

np.int64(8)

In [51]:
print(arr[0:5])
print(arr[:5])
print(arr[5:])

[0 1 2 3 4]
[0 1 2 3 4]
[ 5  6  7  8  9 10]


# Broadcasting

Broadcast a single value to a larger set of values

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [54]:
arr = np.arange(0, 11)

In [56]:
slice_of_array = arr[0:5]
slice_of_array

array([0, 1, 2, 3, 4])

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
slice_of_array[:] = 99
slice_of_array

array([99, 99, 99, 99, 99])

In [59]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr.copy()

# multidimensional

In [60]:
arr_2d = np.array([ [5,10,15], [20,25,30], [35,40,45] ])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [61]:
# Single row
print(arr_2d.shape)

(3, 3)


In [62]:
arr_2d[0]  # First row

array([ 5, 10, 15])

In [63]:
arr_2d[2] # Last row

array([35, 40, 45])

In [66]:
print(arr_2d[1][1])
print(arr_2d[1,1])


25
25


In [67]:
arr_2d[:2]  # Rows upto 2

array([[ 5, 10, 15],
       [20, 25, 30]])

In [68]:
arr_2d[:2,1:] # upto row2, starting col 1 to the end

array([[10, 15],
       [25, 30]])

In [ ]:
# Conditional selection

In [69]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [71]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [72]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [73]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

# Oprations

In [75]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [77]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [79]:
arr / arr

/tmp/ipykernel_2638928/3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [80]:
1 / arr

/tmp/ipykernel_2638928/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [82]:
arr.sum()

np.int64(45)

In [84]:
arr.mean()

np.float64(4.5)

In [86]:
arr2d = np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [88]:
arr2d.sum()

np.int64(300)

In [89]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [90]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [92]:
np.random.rand(2)

array([0.96990985, 0.83244264])

In [93]:
arr2d[2:,1:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [94]:
arr2d[:3, 1:2]

array([[ 1],
       [ 6],
       [11]])

In [95]:
arr2d[:3, 1]

array([ 1,  6, 11])

In [98]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [101]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [103]:
print(mat[:3, 1])
print(mat[:3, 1:2])

[ 2  7 12]
[[ 2]
 [ 7]
 [12]]


In [109]:
print(mat[4])
print(mat[4,:])

[21 22 23 24 25]
[21 22 23 24 25]


In [107]:
mat[3:,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [111]:
print(mat.sum())

325


In [112]:
mat.std()

np.float64(7.211102550927978)

In [114]:
print(mat)
mat.sum(axis=0)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([55, 60, 65, 70, 75])