In [2]:
import random

random.sample(["A", "B", "C"], counts=None, k=2)

['B', 'C']

In [25]:
import os
from pathlib import Path

a = os.listdir(Path("./Malaria/train/infected"))
print(type(a))
print(len(a))

i = 0
for f in a and i < range(10):
    print(f)
    i = i+1

<class 'list'>
13854


TypeError: '<' not supported between instances of 'int' and 'range'

In [18]:
a = [1,2,3,4,5,6]
print(len(a), a)
print(a[:len(a)])
print(a[2:len(a)])
print(a[1:-3])

a.append(7)
print(len(a), a[1:-3])


6 [1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]
[3, 4, 5, 6]
[2, 3]
7 [2, 3, 4]


In [46]:
from sklearn.utils import shuffle

A = [1,2,3,4,5]
B = [11,22,33,44,55]
C = ["A", "B", "C", "D", "E"]
D = ["a", "b", "c", "d", "e"]

ABr, CDr = shuffle(A+B, C+D, random_state=0)
print(ABr)
print(CDr)
for i,j in zip(ABr, CDr):
    print(i, j)

[3, 55, 22, 5, 1, 4, 2, 33, 44, 11]
['C', 'e', 'b', 'E', 'A', 'D', 'B', 'c', 'd', 'a']
3 C
55 e
22 b
5 E
1 A
4 D
2 B
33 c
44 d
11 a


In [44]:
A+B

[1, 2, 3, 4, 5, 11, 22, 33, 44, 55]

In [47]:
import numpy as np

# Create a multidimensional NumPy array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Find the maximum value in the array
max_value = np.amax(array)

# Print the maximum value
print("The maximum value in the array is:", max_value)

The maximum value in the array is: 9


In [48]:
import tensorflow as tf
from tensorflow.keras.layers import Input, Conv2D, Flatten, Dense
from tensorflow.keras.models import Model

# Define the input shape (height, width, channels)
input_shape = (64, 64, 3)  # Example: 64x64 RGB images

# Define the input layer
inputs = Input(shape=input_shape)

# Add a convolutional layer
x = Conv2D(filters=32, kernel_size=(3, 3), activation='relu')(inputs)

# Continue building the model (for example, flattening and adding dense layers)
x = Flatten()(x)
x = Dense(units=10, activation='softmax')(x)

# Create the model
model = Model(inputs=inputs, outputs=x)

# Summary of the model
model.summary()

2025-03-31 23:59:17.594363: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-03-31 23:59:17.616814: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1743458357.629821  625518 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1743458357.634449  625518 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-31 23:59:17.648292: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 64, 64, 3)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d (Conv2D)                 │ (None, 62, 62, 32)     │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 123008)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 10)             │     1,230,090 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,230,986 (4.70 MB)

 Trainable params: 1,230,986 (4.70 MB)

 Non-trainable params: 0 (0.00 B)

In [3]:
import numpy as np
l = [1,2,3,4,5]
a = np.array([1,2,3,4,5])
print(type(a), a)

<class 'numpy.ndarray'> [1 2 3 4 5]


In [13]:
b = (a<3).astype(int)
print(b)

[1 1 0 0 0]


In [14]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
array.shape

(16,)

In [15]:
array.reshape((16,1))
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [18]:
aa = np.array([[0.1], [0.9], [0.9], [0.17], [0.99], [1.0] ])
aa.shape

(6, 1)

In [19]:
aa_1 = (aa >=0.9).astype(int)
aa_1

array([[0],
       [1],
       [1],
       [0],
       [1],
       [1]])

In [25]:
aa_1 = aa.reshape(aa.shape[0],)
aa_1

array([2.27455075e-05, 9.99987721e-01, 9.99975443e-01, 1.76307872e-01,
       9.99997854e-01, 1.00000000e+00])

In [21]:
aa_2 = (aa_1 >=0.9).astype(int)
aa_2

array([0, 1, 1, 0, 1, 1])

In [27]:
aa_3 = aa.flatten()
aa_3

array([2.27455075e-05, 9.99987721e-01, 9.99975443e-01, 1.76307872e-01,
       9.99997854e-01, 1.00000000e+00])

In [29]:
a = [1,2,None, None, 4,5]
for i in a:
    if i:
        print(i)

1
2
4
5


In [6]:
import numpy as np
actual = np.array([1,2,3,4,5])
predicted = np.array([1,0,3,4,0])
for i, (a,p) in enumerate(zip(actual, predicted)):
    print(i, a, p)
    if a != p:
        print(f" --> {i}")

0 1 1
1 2 0
 --> 1
2 3 3
3 4 4
4 5 0
 --> 4


In [10]:
res = ((actual == 3) & (predicted == 3))
print(res)

[False False  True False False]


In [35]:
import numpy as np
X = np.array([11,12,13,14,15,16])
actu = np.array([1,1,1,0,0,0])
pred = np.array([1,0,0,0,0,1])
for i, (a,p) in enumerate(zip(actu, pred)):
    print(i, a, p)
    if a != p:
        print(f" --> {i}")

fp = ((actu == 0) & (pred == 1))
fn = ((actu == 1) & (pred == 0))
print("FN", fn)
print("FP", fp)

0 1 1
1 1 0
 --> 1
2 1 0
 --> 2
3 0 0
4 0 0
5 0 1
 --> 5
FN [False  True  True False False False]
FP [False False False False False  True]


In [29]:
fp_X = X[np.where(fp)]
print(type(fp_X))
print(fp_X)
fn_X = X[np.where(fn)]
print(type(fn_X))
print(fn_X)


<class 'numpy.ndarray'>
[16]
<class 'numpy.ndarray'>
[12 13]


In [16]:
print(fp_X)

(array([5]),)


In [33]:
print(X[(actu == 0) & (pred == 1)])
print(type(X[fp]))

[16]
<class 'numpy.ndarray'>


In [37]:
min([3, 2, 3, 3])


2

In [74]:
col = []
col.append(("A", 1, 11, 111))
col.append(("B", 2, 22, 222))
col.append(("C", 2, 33, 666))
col.append(("D", 4, 44, 444))
col.append(("E", 5, 55, 555))

aa = np.array(col)
aa_t = aa.transpose()
print(aa_t[1])
bb = aa_t[(aa_t[1]==0.99)]
print(bb)

['1' '2' '2' '4' '5']


IndexError: boolean index did not match indexed array along axis 0; size of axis is 4 but size of corresponding boolean axis is 5

In [61]:
aa_t
print(aa_t)

[['A' 'B' 'C' 'D' 'E']
 ['1' '2' '3' '4' '5']
 ['11' '22' '33' '44' '55']
 ['111' '222' '666' '444' '555']]


In [62]:
aa_t[3]

array(['111', '222', '666', '444', '555'], dtype='<U21')

In [63]:
np.argmax(aa_t[3])

np.int64(2)

In [66]:
aaa = np.argmax(np.array(col).transpose()[3])
print(aaa)
print(col[aaa])

2
('C', 3, 33, 666)


In [3]:
from datetime import datetime
datetime.now().strftime('%Y%m%d_%H%M%S')

'20250403_181834'

In [1]:
import pandas as pd
df = pd.DataFrame(data = {
    "aa": ['a', 'b', 'c'],
    "v1": [1, 2, 3],
    "v2": [11, 22, 33],
})
df

aa  v1  v2
0  a   1  11
1  b   2  22
2  c   3  33

In [4]:
df["aa"].repeat(2).reset_index()


index aa
0      0  a
1      0  a
2      1  b
3      1  b
4      2  c
5      2  c

In [2]:
df_new = pd.DataFrame(data = {
    "aa": df["aa"].repeat(2),
    "v": pd.concat([df["v1"], df["v2"]]),
})

df_new

ValueError: cannot reindex on an axis with duplicate labels

In [1]:
from sklearn.util import train_test_split

ModuleNotFoundError: No module named 'sklearn.util'